[package]
name = "scr-axum-cranker-router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7", features = ["default", "ws"] }
futures = "0.3"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4", features = ["util", "filter"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "1.0"
dashmap = "5.0"
uuid = { version = "1.0", features = ["v4"] }
lazy_static = "1.4.0"
axum-macros = { version = "0.4" }
rand = { version = "0.8.5" }

[lib]
crate-type = ["lib"]

[dev-dependencies]
simple_logger = "4.2.0"

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'
codegen-units = 1
lto = true