#!/bin/bash
# ci_verify.sh - CI verification script for scr-axum-cranker-router
# Auto-generated by generate_ci.sh. Do not edit manually.
set -e

echo "=== Starting CI Verification ==="

# 1. Environment Check
echo "Checking environment dependencies..."
if ! command -v cargo &> /dev/null; then
    export PATH="$PATH:$HOME/.cargo/bin"
fi
for cmd in git java mvn cargo; do
    if ! command -v "$cmd" &> /dev/null; then
        echo "Error: Required command '$cmd' is not installed or not in PATH." >&2
        exit 1
    fi
done
echo "Environment dependencies verified: git, java, mvn, cargo are available."

# 2. Paths and Directories Setup
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Resolve temporary directory
if [ -z "$CI_TMP_DIR" ]; then
    CI_TMP_DIR="$SCRIPT_DIR/target/ci_tmp"
fi

echo "CI Temporary directory: $CI_TMP_DIR"

# Clean up any existing temp directory
rm -rf "$CI_TMP_DIR"
mkdir -p "$CI_TMP_DIR"

# Set up trap to kill leftover Rust processes on exit
cleanup_rust_processes() {
    echo "=== Cleaning leftover unified_router_server processes ==="
    if [[ "$OSTYPE" == "cygwin" || "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
        taskkill //F //IM unified_router_server.exe 2>/dev/null || true
    else
        pkill -9 -f unified_router_server 2>/dev/null || true
    fi
}
trap cleanup_rust_processes EXIT

# 3. Retrieve origin URLs
echo "Retrieving git remote URLs..."
CONNECTOR_REMOTE_URL="${CRANKER_CONNECTOR_REMOTE_URL:-git@github.com:hsbc/cranker-connector.git}"
MU_ROUTER_REMOTE_URL="${MU_CRANKER_ROUTER_REMOTE_URL:-git@github.com:hsbc/mu-cranker-router.git}"

CONNECTOR_COMMIT="1dc059c11a93800b0b69172d165456d93f7dfbc3"
MU_ROUTER_COMMIT="b45eb9df14eaf273c705b4cda6208f68f1ff57dc"
CONNECTOR_BRANCH="master"
MU_ROUTER_BRANCH="master"

echo "cranker-connector remote URL: $CONNECTOR_REMOTE_URL"
echo "mu-cranker-router remote URL: $MU_ROUTER_REMOTE_URL"

# 4. Clone Repositories into ci_tmp
echo "=== Cloning repositories to ci_tmp ==="
git clone "$CONNECTOR_REMOTE_URL" "$CI_TMP_DIR/cranker-connector"
git clone "$MU_ROUTER_REMOTE_URL" "$CI_TMP_DIR/mu-cranker-router"

# Checkout pinned commits to ensure patch compatibility
echo "Checking out pinned commit $CONNECTOR_COMMIT for cranker-connector..."
git -C "$CI_TMP_DIR/cranker-connector" checkout "$CONNECTOR_COMMIT"

echo "Checking out pinned commit $MU_ROUTER_COMMIT for mu-cranker-router..."
git -C "$CI_TMP_DIR/mu-cranker-router" checkout "$MU_ROUTER_COMMIT"

# 5. Apply Patches
echo "=== Applying patches to cloned repositories ==="
git -C "$CI_TMP_DIR/cranker-connector" apply "$SCRIPT_DIR/patches/cranker-connector.patch"
git -C "$CI_TMP_DIR/mu-cranker-router" apply "$SCRIPT_DIR/patches/mu-cranker-router.patch"

# 6. Build Router Server Binary
echo "=== Building scr-axum-cranker-router bin ==="
cargo build --release --example unified_router_server

# Locate binary extension (.exe on Windows)
EXE_EXT=""
if [ -f "$SCRIPT_DIR/target/release/examples/unified_router_server.exe" ]; then
    EXE_EXT=".exe"
fi

# Copy built binary to temp dir
cp "$SCRIPT_DIR/target/release/examples/unified_router_server${EXE_EXT}" "$CI_TMP_DIR/unified_router_server${EXE_EXT}"

# 7. Build & Install mu-cranker-router and cranker-connector
echo "=== Building and installing mu-cranker-router ==="
mvn -f "$CI_TMP_DIR/mu-cranker-router/pom.xml" clean install -DskipTests -Dmaven.javadoc.skip=true -Dsource.skip=true

echo "=== Building cranker-connector uber jar ==="
mvn -f "$CI_TMP_DIR/cranker-connector/pom.xml" clean package -DskipTests -Dmaven.javadoc.skip=true -Dsource.skip=true

# Find the built uber jar
CONNECTOR_JAR=$(find "$CI_TMP_DIR/cranker-connector/target" -name "*uber.jar" | head -n 1)
if [ -z "$CONNECTOR_JAR" ]; then
    echo "Error: Failed to find built uber jar in cranker-connector/target." >&2
    exit 1
fi
cp "$CONNECTOR_JAR" "$CI_TMP_DIR/connector-uber.jar"

# 8. Run Java mu-cranker-router tests in all 3 modes
echo "=== Running Java mu-cranker-router tests (Java Mode) ==="
[[ "$RUN_JAVA_TEST" == "true" ]] \
  && mvn -f "$CI_TMP_DIR/mu-cranker-router/pom.xml" clean test -Dmaven.javadoc.skip=true -Dsource.skip=true \
  || echo "Skipped Java router test run since no RUN_JAVA_TEST env var set"
cleanup_rust_processes

# export RUST_ROUTER_SERVER_EXE="$CI_TMP_DIR/unified_router_server${EXE_EXT}"

echo "=== Running Java mu-cranker-router tests (Rust Mode, TLS off) ==="
[[ "$RUN_TLS_OFF_TEST" == "true" ]] \
  && RUST_ROUTER_SERVER_EXE="$CI_TMP_DIR/unified_router_server${EXE_EXT}" \
     mvn -f "$CI_TMP_DIR/mu-cranker-router/pom.xml" clean test -Dcranker.router.rust=true \
     -Dmaven.javadoc.skip=true -Dsource.skip=true \
  || echo "Skipped Rust router test run since no RUN_TLS_OFF_TEST env var set"
cleanup_rust_processes

echo "=== Running Java mu-cranker-router tests (Rust Mode, TLS on) ==="
RUST_ROUTER_SERVER_EXE="$CI_TMP_DIR/unified_router_server${EXE_EXT}" \
  mvn -f "$CI_TMP_DIR/mu-cranker-router/pom.xml" clean test -Dcranker.router.rust=true \
      -Dcranker.router.tls=true -Dmaven.javadoc.skip=true -Dsource.skip=true
cleanup_rust_processes

# 8.5. Run Java cranker-connector tests in all 3 modes
echo "=== Running Java cranker-connector tests (Java Mode) ==="
[[ "$RUN_JAVA_TEST" == "true" ]] \
  && mvn -f "$CI_TMP_DIR/cranker-connector/pom.xml" clean test -Dmaven.javadoc.skip=true -Dsource.skip=true \
  || echo "Skipped Java router test run since no RUN_JAVA_TEST env var set"
cleanup_rust_processes

echo "=== Running Java cranker-connector tests (Rust Mode, TLS off) ==="
[[ "$RUN_TLS_OFF_TEST" == "true" ]] \
  && RUST_ROUTER_SERVER_EXE="$CI_TMP_DIR/unified_router_server${EXE_EXT}" \
     mvn -f "$CI_TMP_DIR/cranker-connector/pom.xml" clean test -Dcranker.router.rust=true \
         -Dmaven.javadoc.skip=true -Dsource.skip=true \
  || echo "Skipped Rust connector test run since no RUN_TLS_OFF_TEST env var set"
cleanup_rust_processes

echo "=== Running Java cranker-connector tests (Rust Mode, TLS on) ==="
RUST_ROUTER_SERVER_EXE="$CI_TMP_DIR/unified_router_server${EXE_EXT}" \
  mvn -f "$CI_TMP_DIR/cranker-connector/pom.xml" clean test -Dcranker.router.rust=true \
      -Dcranker.router.tls=true -Dmaven.javadoc.skip=true -Dsource.skip=true
cleanup_rust_processes

# 9. Run Rust unit & integration tests
echo "=== Running scr-axum-cranker-router tests ==="
export CRANKER_CONNECTOR_JAR="$CI_TMP_DIR/connector-uber.jar"
cargo test --lib -- --nocapture

# 9.5. Clean up temporary files after all tests passed successfully
echo "=== Cleaning up temporary files ==="
rm -rf "$CI_TMP_DIR"
echo "=== Cleanup completed ==="

echo "=== CI Verification Passed Successfully! ==="
