#!/bin/bash
# generate_ci.sh - Generates ci_verify.sh and patch files for scr-axum-cranker-router CI
#
# This script must be run from the scr-axum-cranker-router/ directory.
# It expects the following folder structure in the parent directory:
#   ../cranker-connector/
#   ../mu-cranker-router/
#   ../scr-axum-cranker-router/   (this project)
#
# Each sibling must be a git repository on a dev branch with changes over origin/master.

set -e

echo "=== Generating CI Verification Script ==="

# 1. Verify working directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ "$(basename "$SCRIPT_DIR")" != "scr-axum-cranker-router" ]; then
    echo "Error: This script must be placed and run from the scr-axum-cranker-router/ directory." >&2
    exit 1
fi

WORKSPACE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# 2. Verify folder structure
echo "Verifying folder structure..."
for dir in cranker-connector mu-cranker-router; do
    if [ ! -d "$WORKSPACE_DIR/$dir" ]; then
        echo "Error: Expected sibling directory '$dir' not found at $WORKSPACE_DIR/$dir" >&2
        exit 1
    fi
    if ! git -C "$WORKSPACE_DIR/$dir" rev-parse --git-dir &> /dev/null; then
        echo "Error: '$dir' is not a git repository." >&2
        exit 1
    fi
done
echo "Folder structure verified: cranker-connector, mu-cranker-router found."

# 3. Detect remote URLs
echo "Detecting remote URLs..."
CONNECTOR_REMOTE_URL=$(git -C "$WORKSPACE_DIR/cranker-connector" remote get-url origin 2>/dev/null)
MU_ROUTER_REMOTE_URL=$(git -C "$WORKSPACE_DIR/mu-cranker-router" remote get-url origin 2>/dev/null)

if [ -z "$CONNECTOR_REMOTE_URL" ] || [ -z "$MU_ROUTER_REMOTE_URL" ]; then
    echo "Error: Could not determine origin remote URL for one or both repositories." >&2
    exit 1
fi

echo "  cranker-connector origin: $CONNECTOR_REMOTE_URL"
echo "  mu-cranker-router origin: $MU_ROUTER_REMOTE_URL"

# 4. Detect default branch and commit IDs
echo "Detecting main/master branch commit IDs..."

detect_default_branch() {
    local repo_dir="$1"
    # Try origin/master first, then origin/main
    if git -C "$repo_dir" rev-parse --verify origin/master &>/dev/null; then
        echo "master"
    elif git -C "$repo_dir" rev-parse --verify origin/main &>/dev/null; then
        echo "main"
    else
        echo ""
    fi
}

CONNECTOR_BRANCH=$(detect_default_branch "$WORKSPACE_DIR/cranker-connector")
MU_ROUTER_BRANCH=$(detect_default_branch "$WORKSPACE_DIR/mu-cranker-router")

if [ -z "$CONNECTOR_BRANCH" ] || [ -z "$MU_ROUTER_BRANCH" ]; then
    echo "Error: Could not detect main/master branch for one or both repositories." >&2
    exit 1
fi

CONNECTOR_COMMIT=$(git -C "$WORKSPACE_DIR/cranker-connector" rev-parse "origin/$CONNECTOR_BRANCH")
MU_ROUTER_COMMIT=$(git -C "$WORKSPACE_DIR/mu-cranker-router" rev-parse "origin/$MU_ROUTER_BRANCH")

echo "  cranker-connector: origin/$CONNECTOR_BRANCH @ $CONNECTOR_COMMIT"
echo "  mu-cranker-router: origin/$MU_ROUTER_BRANCH @ $MU_ROUTER_COMMIT"

# 5. Generate patch files
echo "Generating patch files..."
mkdir -p "$SCRIPT_DIR/patches"

git -C "$WORKSPACE_DIR/cranker-connector" diff "origin/$CONNECTOR_BRANCH" > "$SCRIPT_DIR/patches/cranker-connector.patch"
git -C "$WORKSPACE_DIR/mu-cranker-router" diff "origin/$MU_ROUTER_BRANCH" > "$SCRIPT_DIR/patches/mu-cranker-router.patch"

CONNECTOR_PATCH_LINES=$(wc -l < "$SCRIPT_DIR/patches/cranker-connector.patch")
MU_ROUTER_PATCH_LINES=$(wc -l < "$SCRIPT_DIR/patches/mu-cranker-router.patch")

echo "  cranker-connector.patch: $CONNECTOR_PATCH_LINES lines"
echo "  mu-cranker-router.patch: $MU_ROUTER_PATCH_LINES lines"

if [ "$CONNECTOR_PATCH_LINES" -eq 0 ] && [ "$MU_ROUTER_PATCH_LINES" -eq 0 ]; then
    echo "Warning: Both patches are empty. Are you on the correct dev branch?" >&2
fi

# 6. Generate ci_verify.sh
echo "Generating ci_verify.sh..."

cat > "$SCRIPT_DIR/ci_verify.sh" << 'SCRIPT_HEADER'
#!/bin/bash
# ci_verify.sh - CI verification script for scr-axum-cranker-router
# Auto-generated by generate_ci.sh. Do not edit manually.
set -e

echo "=== Starting CI Verification ==="

# 1. Environment Check
echo "Checking environment dependencies..."
if ! command -v cargo &> /dev/null; then
    export PATH="$PATH:$HOME/.cargo/bin"
fi
for cmd in git java mvn cargo; do
    if ! command -v "$cmd" &> /dev/null; then
        echo "Error: Required command '$cmd' is not installed or not in PATH." >&2
        exit 1
    fi
done
echo "Environment dependencies verified: git, java, mvn, cargo are available."

# 2. Paths and Directories Setup
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Resolve temporary directory
if [ -z "$CI_TMP_DIR" ]; then
    CI_TMP_DIR="$SCRIPT_DIR/target/ci_tmp"
fi

echo "CI Temporary directory: $CI_TMP_DIR"

# Clean up any existing temp directory
rm -rf "$CI_TMP_DIR"
mkdir -p "$CI_TMP_DIR"

# Set up trap to clean up on exit
cleanup() {
    echo "=== Cleaning up temporary files ==="
    rm -rf "$CI_TMP_DIR"
    echo "=== Cleanup completed ==="
}
trap cleanup EXIT

# 3. Retrieve origin URLs
echo "Retrieving git remote URLs..."
SCRIPT_HEADER

# Inject the detected values
cat >> "$SCRIPT_DIR/ci_verify.sh" << SCRIPT_VARS
CONNECTOR_REMOTE_URL="\${CRANKER_CONNECTOR_REMOTE_URL:-$CONNECTOR_REMOTE_URL}"
MU_ROUTER_REMOTE_URL="\${MU_CRANKER_ROUTER_REMOTE_URL:-$MU_ROUTER_REMOTE_URL}"

CONNECTOR_COMMIT="$CONNECTOR_COMMIT"
MU_ROUTER_COMMIT="$MU_ROUTER_COMMIT"
CONNECTOR_BRANCH="$CONNECTOR_BRANCH"
MU_ROUTER_BRANCH="$MU_ROUTER_BRANCH"
SCRIPT_VARS

cat >> "$SCRIPT_DIR/ci_verify.sh" << 'SCRIPT_BODY'

echo "cranker-connector remote URL: $CONNECTOR_REMOTE_URL"
echo "mu-cranker-router remote URL: $MU_ROUTER_REMOTE_URL"

# 4. Clone Repositories into ci_tmp
echo "=== Cloning repositories to ci_tmp ==="
git clone "$CONNECTOR_REMOTE_URL" "$CI_TMP_DIR/cranker-connector"
git clone "$MU_ROUTER_REMOTE_URL" "$CI_TMP_DIR/mu-cranker-router"

# Checkout pinned commits to ensure patch compatibility
echo "Checking out pinned commit $CONNECTOR_COMMIT for cranker-connector..."
git -C "$CI_TMP_DIR/cranker-connector" checkout "$CONNECTOR_COMMIT"

echo "Checking out pinned commit $MU_ROUTER_COMMIT for mu-cranker-router..."
git -C "$CI_TMP_DIR/mu-cranker-router" checkout "$MU_ROUTER_COMMIT"

# 5. Apply Patches
echo "=== Applying patches to cloned repositories ==="
git -C "$CI_TMP_DIR/cranker-connector" apply "$SCRIPT_DIR/patches/cranker-connector.patch"
git -C "$CI_TMP_DIR/mu-cranker-router" apply "$SCRIPT_DIR/patches/mu-cranker-router.patch"

# 6. Build Router Server Binary
echo "=== Building scr-axum-cranker-router bin ==="
cargo build --release --bin router_server

# Locate binary extension (.exe on Windows)
EXE_EXT=""
if [ -f "$SCRIPT_DIR/target/release/router_server.exe" ]; then
    EXE_EXT=".exe"
fi

# Copy built binary to temp dir
cp "$SCRIPT_DIR/target/release/router_server${EXE_EXT}" "$CI_TMP_DIR/router_server${EXE_EXT}"

# 7. Build cranker-connector Uber Jar
echo "=== Building cranker-connector uber jar ==="
mvn -f "$CI_TMP_DIR/cranker-connector/pom.xml" clean package -DskipTests -Dmaven.javadoc.skip=true -Dsource.skip=true

# Find the built uber jar
CONNECTOR_JAR=$(find "$CI_TMP_DIR/cranker-connector/target" -name "*uber.jar" | head -n 1)
if [ -z "$CONNECTOR_JAR" ]; then
    echo "Error: Failed to find built uber jar in cranker-connector/target." >&2
    exit 1
fi
cp "$CONNECTOR_JAR" "$CI_TMP_DIR/connector-uber.jar"

# 8. Run Java mu-cranker-router tests against Rust router_server
echo "=== Running Java mu-cranker-router tests ==="
export CRANKER_ROUTER_RUST=true
export RUST_ROUTER_SERVER_EXE="$CI_TMP_DIR/router_server${EXE_EXT}"

mvn -f "$CI_TMP_DIR/mu-cranker-router/pom.xml" clean test -Dcranker.router.rust=true -Dmaven.javadoc.skip=true -Dsource.skip=true

# 9. Run Rust unit & integration tests
echo "=== Running scr-axum-cranker-router tests ==="
export CRANKER_CONNECTOR_JAR="$CI_TMP_DIR/connector-uber.jar"
cargo test --lib -- --nocapture

echo "=== CI Verification Passed Successfully! ==="
SCRIPT_BODY

chmod +x "$SCRIPT_DIR/ci_verify.sh"

echo ""
echo "=== Generation Complete ==="
echo "Generated files:"
echo "  ci_verify.sh"
echo "  patches/cranker-connector.patch ($CONNECTOR_PATCH_LINES lines)"
echo "  patches/mu-cranker-router.patch ($MU_ROUTER_PATCH_LINES lines)"
echo ""
echo "Pinned commits:"
echo "  cranker-connector: $CONNECTOR_COMMIT (origin/$CONNECTOR_BRANCH)"
echo "  mu-cranker-router: $MU_ROUTER_COMMIT (origin/$MU_ROUTER_BRANCH)"
